#!/bin/bash

case "$1" in
    PHP_CodeSniffer)
        cd ${TESTING_SITE_DIR}
        ./vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md ./web/modules/rdf_entity
        exit $?
        ;;
    PHPUnit)
        cd ${TESTING_SITE_DIR}/web
        ../vendor/bin/phpunit
        exit $?
        ;;
    *)
        echo "Unknown test '$1'"
        exit 1
esac
