#!/bin/bash

case "$1" in
    PHP_CodeSniffer)
        cd ${TESTING_SITE_DIR}
        ./vendor/bin/phpcs --config-set installed_paths ../../vendor/drupal/coder/coder_sniffer
        ./vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md ./web/modules/rdf_entity
        exit $?
        ;;
    PHPUnit)
        cd ${TESTING_SITE_DIR}
        ./vendor/bin/drush site:install testing --yes --root=${TESTING_SITE_DIR}/web --db-url=mysql://root:@127.0.0.1/rdf_entity_test
        chmod 0775 ${TESTING_SITE_DIR}/web/sites/default/settings.php
        cat ${TRAVIS_BUILD_DIR}/tests/travis-ci/fixtures/connection.txt >> ${TESTING_SITE_DIR}/web/sites/default/settings.php
        ./vendor/bin/drush pm:enable rdf_entity --yes --root=${TESTING_SITE_DIR}/web
        # Start the webserver.
        cd ${TESTING_SITE_DIR}/web
        nohup php -S localhost:8888 > /dev/null 2>&1 &
        # Wait until the web server is responding.
        until curl -s localhost:8888; do true; done > /dev/null
        ../vendor/bin/phpunit
        exit $?
        ;;
    *)
        echo "Unknown test '$1'"
        exit 1
esac
